import cs345.bdsl._

object InventoryTest extends Bdsl {

  def main(args: Array[String]): Unit = {
    CREATE NEW EMPLOYEE WITH NAME AS "John Smith" WITH RANK AS 1; // EMP ID: 1
    PRINT ALL EMPLOYEE;

    CREATE NEW CLIENT WITH NAME AS "Jane Smith" WITH BALANCE AS 123.20; // CLI ID : 2
    CREATE NEW CLIENT WITH NAME AS "Bob Jr"; // CLI ID : 3
    PRINT ALL CLIENT;

    CREATE NEW INVENTORY WITH NAME AS "ITEM 1" WITH QUANTITY AS 323 WITH TOTAL_COST AS 2342.20; // INV ID : 1
    CREATE NEW INVENTORY WITH NAME AS "ITEM 2" WITH QUANTITY AS 500 WITH TOTAL_COST AS 1000.00; // INV ID : 2
    PRINT ALL INVENTORY;

    CREATE NEW SHIPMENT OF_ITEM 1 FOR_AMOUNT 100 FOR_COST 1000.00;// SHI ID : 1
    CREATE NEW SHIPMENT OF_ITEM 1 FOR_AMOUNT 100 FOR_COST 1000.00;// SHI ID : 2
    PRINT ALL SHIPMENT;
    PRINT ALL INVENTORY;
    UPDATE SHIPMENT 1 MODIFY TOTAL_COST TO 500.00;
    REMOVE SHIPMENT 2;
    PRINT ALL SHIPMENT;
    PRINT ALL INVENTORY;

    CREATE NEW PURCHASE FOR_CLIENT 2 OF_ITEM 1 FOR_AMOUNT 200 FOR_COST 3423.12 REVIEWED_BY 1; // PUR ID : 1
    CREATE NEW PURCHASE FOR_CLIENT 3 OF_ITEM 2 FOR_AMOUNT 100 FOR_COST 1000.00 REVIEWED_BY 1; // PUR ID : 2
    CREATE NEW PURCHASE FOR_CLIENT 3 OF_ITEM 2 FOR_AMOUNT 1 FOR_COST 100.00 REVIEWED_BY 1; // PUR ID : 3
    PRINT ALL PURCHASE;
    PRINT ALL CLIENT;
    PRINT ALL INVENTORY;
    UPDATE PURCHASE 1 MODIFY TOTAL_COST TO 3000.15;
    REMOVE PURCHASE 3;
    PRINT ALL PURCHASE;
    PRINT ALL CLIENT;
    PRINT ALL INVENTORY;

    CREATE NEW PAYMENT FOR_CLIENT 2 FOR_AMOUNT 3000.15 REVIEWED_BY 1; // PAY ID : 1
    CREATE NEW PAYMENT FOR_CLIENT 3 FOR_AMOUNT 100.00 REVIEWED_BY 1; // PAY ID : 2
    PRINT ALL PAYMENT;
    PRINT ALL CLIENT;
    UPDATE PAYMENT 1 MODIFY AMOUNT TO 200.00;
    REMOVE PAYMENT 2;
    PRINT ALL PAYMENT;
    PRINT ALL CLIENT;


  }

}