val bdsl = new cs345.bdsl.Bdsl
import bdsl._
import cs345.bdsl._


CREATE NEW EMPLOYEE WITH NAME AS "Nathan Bain" WITH RANK AS 10
PRINT ALL EMPLOYEE
UPDATE EMPLOYEE 1 MODIFY RANK TO 11 MODIFY PAY TO 12.20
PRINT ALL EMPLOYEE
CREATE NEW CLIENT WITH NAME AS "Microsoft"
CREATE NEW MEETING WITH NAME AS "Company meeting" WITH START AS "12/09/2016 01:00 PM" WITH DURATION AS 90
CREATE NEW MEETING WITH NAME AS "Meeting with Microsoft" WITH CLIENT_ID AS 2 WITH START AS "12/09/2016 01:00 PM" WITH DURATION AS 90
PRINT ALL
IMPORT FROM "employees.csv" TO EMPLOYEE
PRINT ALL
BATCH ALL EMPLOYEE WHERE RANK LESSTHAN 20 REMOVE
BATCH ALL EMPLOYEE WHERE PAY GREATERTHAN 20.00 REMOVE
PRINT ALL
BATCH ALL EMPLOYEE WHERE PAY LESSTHANEQUAL 13.00 MODIFY PAY TO 13.00
PRINT ALL
ASSIGN EMPLOYEE 1 TO EVENT MEETING 2
PRINT ALL
BATCH ALL EMPLOYEE ASSIGN EVENT MEETING 1
PRINT ALL
